name: Gitlab Runner Service
on: [repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space
        run: df -h
      - name: Gitlab Runner
        uses: addshore/gitlab-runner-action@main
        with:
          registration-token: "${{ github.event.client_payload.registration_token }}"
          docker-image: "docker:19.03.12"
          name: ${{ github.run_id }}
          tag-list: "${{ github.event.client_payload.tag_list }}"
          gitlab-instance: "${{ github.event.client_payload.url }}"
